#' SomaLogic \pkg{ggplot2} Theme
#'
#' This \pkg{ggplot2} compatible theme contains specific settings
#' based on the base theme [theme_bw()] and incorporates
#' elements based on requirements from SomaLogic's Commercial and Marketing teams.
#' It allows a consistent look, feel, and design for all
#' graphics generated by the SomaLogic Bioinformatics Team. 
#' It includes a framework for `gg`-style
#' functions for plot consistency and standardization.
#'
#' @param base_size Numeric. SomaLogic default is 12. \pkg{ggplot2} default is 11.
#'   See [theme_bw()].
#' @param base_family Character. See [theme_bw()] and the examples.
#' @param legend.position Character. One of "none", "top", "right", "bottom",
#'   or "left". See [theme()].
#' @param hjust Numeric \verb{[0, 1]}. Horizontal adjustment for the
#'   title. Left = 0, Center = 0.5, Right = 1.
#' @param aspect_ratio Character. One of "landscape" (16:9),
#'   "profile" (8.5:11), or "none" (default). The "landscape" and "profile"
#'   options were requested by Marketing and can/should be used to
#'   finalize standard plots.
#' @author Stu Field, Leigh Alexander
#' @examples
#' library(ggplot2)
#'
#' # default ggplot2 theme; the `gg` object
#' gg$point
#' gg$bar
#' gg$box
#'
#' # ---------------
#' # SomaLogic Theme
#' # ---------------
#' gg$point + theme_soma()
#' gg$box + theme_soma()
#'
#' # The `theme_soma()` allows some arguments:
#' #   1) put legend back to default `ggplot2` position
#' #   2) make font sizes larger: 11 -> 15
#' gg$point + theme_soma(legend.position = "right", base_size = 15)
#'
#' # -----------------------
#' # SomaLogic Color Palette
#' # -----------------------
#' # Combined with the `discrete` color palette
#' gg$point + theme_soma() + scale_color_soma()  # note: `color`
#' gg$bar + theme_soma() + scale_fill_soma()     # note: `fill`
#' gg$box + theme_soma() + scale_fill_soma()     # note: `fill`
#'
#' # Combined with `continuous` color palette
#' # Continuous `color`
#' pt <- mtcars |>
#'   ggplot(aes(x = wt, y = mpg, color = cyl)) +
#'   geom_point(size = 4)
#' pt
#' pt + scale_continuous_color_soma()   # note: `color`
#'
#' # Continuous `fill`
#' h <- data.frame(x = withr::with_seed(101, rnorm(500))) |>
#'   ggplot(aes(x, fill = after_stat(count))) +
#'   geom_histogram()
#' h
#' h + scale_continuous_fill_soma()     # note: `fill`
#' @importFrom ggplot2 theme_bw theme element_text rel unit
#' @importFrom ggplot2 element_rect element_line element_blank
#' @export
theme_soma <- function(base_size = 12,
                       base_family = "",
                       legend.position = c("top", "none", "right", "left", "bottom"),
                       hjust = 0,
                       aspect_ratio = c("none", "landscape", "profile")) {

  aspect_ratio    <- match.arg(aspect_ratio)
  legend.position <- match.arg(legend.position)
  ar              <- switch(aspect_ratio,
                         "landscape" = 9 / 16,
                         "profile"   = 11 / 8.5,
                         "none"      = NULL)
  ggplot2::theme_bw(base_size      = base_size,
                    base_family    = base_family,
                    base_line_size = base_size / 20) +
    ggplot2::theme(
      plot.background   = ggplot2::element_rect(fill = "transparent", color = NA),
      plot.title        = ggplot2::element_text(hjust = hjust,
                                                size = ggplot2::rel(1.5)),
      legend.position   = legend.position,
      legend.background = ggplot2::element_rect(fill = "transparent", color = NA),
      legend.key        = ggplot2::element_rect(fill = "transparent", color = NA),
      aspect.ratio      = ar,
      # axis.line         = ggplot2::element_line(color  = soma_colors$lightgrey,
      #                                      linewidth   = ggplot2::unit(1, "points")),
      axis.ticks        = ggplot2::element_line(color = soma_colors$lightgrey),
      axis.ticks.length = ggplot2::unit(8, "points"),
      axis.text.x       = ggplot2::element_text(color = soma_colors$lightgrey,
      # family = "Arial",   # uncomment when I get the fonts working
                                                size = ggplot2::rel(1.2)),
      axis.text.y       = ggplot2::element_text(color = soma_colors$lightgrey,
      # family = "Arial",  # uncomment when I get the fonts working
                                                size = ggplot2::rel(1.2)),
      axis.line         = ggplot2::element_line(color = soma_colors$lightgrey,
                                                linewidth = 0.2),

      panel.background  = ggplot2::element_rect(fill = "transparent", color = NA),
      panel.border      = ggplot2::element_blank(),
      panel.grid        = ggplot2::element_line(color = "#B9BDBE",
                                                linewidth = 0.2),
      # no filled background for faceted plots
      strip.background  = element_blank()
    )
}
